<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240920100317 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE issue_assignee DROP CONSTRAINT fk_ab35d6a75e7aa58c');
        $this->addSql('ALTER TABLE issue_assignee DROP CONSTRAINT fk_ab35d6a764ab9629');
        $this->addSql('DROP TABLE issue_assignee');
        $this->addSql('ALTER TABLE issue ADD assignee_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE issue ADD CONSTRAINT FK_12AD233E59EC7D60 FOREIGN KEY (assignee_id) REFERENCES project_member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_12AD233E59EC7D60 ON issue (assignee_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE TABLE issue_assignee (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, issue_id INT NOT NULL, project_member_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_ab35d6a764ab9629 ON issue_assignee (project_member_id)');
        $this->addSql('CREATE INDEX idx_ab35d6a75e7aa58c ON issue_assignee (issue_id)');
        $this->addSql('ALTER TABLE issue_assignee ADD CONSTRAINT fk_ab35d6a75e7aa58c FOREIGN KEY (issue_id) REFERENCES issue (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue_assignee ADD CONSTRAINT fk_ab35d6a764ab9629 FOREIGN KEY (project_member_id) REFERENCES project_member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue DROP CONSTRAINT FK_12AD233E59EC7D60');
        $this->addSql('DROP INDEX IDX_12AD233E59EC7D60');
        $this->addSql('ALTER TABLE issue DROP assignee_id');
    }
}
