<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240919095546 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE issue_assignee (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, issue_id INT NOT NULL, project_member_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AB35D6A75E7AA58C ON issue_assignee (issue_id)');
        $this->addSql('CREATE INDEX IDX_AB35D6A764AB9629 ON issue_assignee (project_member_id)');
        $this->addSql('ALTER TABLE issue_assignee ADD CONSTRAINT FK_AB35D6A75E7AA58C FOREIGN KEY (issue_id) REFERENCES issue (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue_assignee ADD CONSTRAINT FK_AB35D6A764AB9629 FOREIGN KEY (project_member_id) REFERENCES project_member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE issue_assignee DROP CONSTRAINT FK_AB35D6A75E7AA58C');
        $this->addSql('ALTER TABLE issue_assignee DROP CONSTRAINT FK_AB35D6A764AB9629');
        $this->addSql('DROP TABLE issue_assignee');
    }
}
