<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241210112303 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE issue_thread_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, issue_id INT NOT NULL, thread_message_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FFB41CE15E7AA58C ON issue_thread_message (issue_id)');
        $this->addSql('CREATE INDEX IDX_FFB41CE1912286A1 ON issue_thread_message (thread_message_id)');
        $this->addSql('ALTER TABLE issue_thread_message ADD CONSTRAINT FK_FFB41CE15E7AA58C FOREIGN KEY (issue_id) REFERENCES issue (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue_thread_message ADD CONSTRAINT FK_FFB41CE1912286A1 FOREIGN KEY (thread_message_id) REFERENCES thread_message (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE issue_thread_message DROP CONSTRAINT FK_FFB41CE15E7AA58C');
        $this->addSql('ALTER TABLE issue_thread_message DROP CONSTRAINT FK_FFB41CE1912286A1');
        $this->addSql('DROP TABLE issue_thread_message');
    }
}
