<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240819100546 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE issue (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, priority INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, issue_column_id INT NOT NULL, project_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_12AD233EFF5D5C9F ON issue (issue_column_id)');
        $this->addSql('CREATE INDEX IDX_12AD233E166D1F9C ON issue (project_id)');
        $this->addSql('CREATE INDEX IDX_12AD233EB03A8386 ON issue (created_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_12AD233E166D1F9C96901F54 ON issue (project_id, number)');
        $this->addSql('CREATE TABLE issue_column (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(40) NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8FA30D598A90ABA9 ON issue_column (key)');
        $this->addSql('ALTER TABLE issue ADD CONSTRAINT FK_12AD233EFF5D5C9F FOREIGN KEY (issue_column_id) REFERENCES issue_column (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue ADD CONSTRAINT FK_12AD233E166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue ADD CONSTRAINT FK_12AD233EB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project ADD issue_autoincrement_id INT DEFAULT 1 NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE issue DROP CONSTRAINT FK_12AD233EFF5D5C9F');
        $this->addSql('ALTER TABLE issue DROP CONSTRAINT FK_12AD233E166D1F9C');
        $this->addSql('ALTER TABLE issue DROP CONSTRAINT FK_12AD233EB03A8386');
        $this->addSql('DROP TABLE issue');
        $this->addSql('DROP TABLE issue_column');
        $this->addSql('ALTER TABLE project DROP issue_autoincrement_id');
    }
}
