<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241017115219 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_sent_email BOOLEAN DEFAULT false NOT NULL, is_read BOOLEAN DEFAULT false NOT NULL, event_id INT NOT NULL, for_user_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3F980AC871F7E88B ON user_notification (event_id)');
        $this->addSql('CREATE INDEX IDX_3F980AC89B5BB4B8 ON user_notification (for_user_id)');
        $this->addSql('ALTER TABLE user_notification ADD CONSTRAINT FK_3F980AC871F7E88B FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_notification ADD CONSTRAINT FK_3F980AC89B5BB4B8 FOREIGN KEY (for_user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE user_notification DROP CONSTRAINT FK_3F980AC871F7E88B');
        $this->addSql('ALTER TABLE user_notification DROP CONSTRAINT FK_3F980AC89B5BB4B8');
        $this->addSql('DROP TABLE user_notification');
    }
}
