<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240822112049 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project_member_role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role_id INT NOT NULL, project_member_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_632E51CDD60322AC ON project_member_role (role_id)');
        $this->addSql('CREATE INDEX IDX_632E51CD64AB9629 ON project_member_role (project_member_id)');
        $this->addSql('CREATE TABLE project_role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(40) NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE project_member_role ADD CONSTRAINT FK_632E51CDD60322AC FOREIGN KEY (role_id) REFERENCES project_role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_member_role ADD CONSTRAINT FK_632E51CD64AB9629 FOREIGN KEY (project_member_id) REFERENCES project_member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE project_member_role DROP CONSTRAINT FK_632E51CDD60322AC');
        $this->addSql('ALTER TABLE project_member_role DROP CONSTRAINT FK_632E51CD64AB9629');
        $this->addSql('DROP TABLE project_member_role');
        $this->addSql('DROP TABLE project_role');
    }
}
