<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250620150038 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE room (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_729F519B166D1F9C ON room (project_id)');
        $this->addSql('CREATE TABLE room_issue (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, room_id INT NOT NULL, issue_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5811829554177093 ON room_issue (room_id)');
        $this->addSql('CREATE INDEX IDX_581182955E7AA58C ON room_issue (issue_id)');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT FK_729F519B166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room_issue ADD CONSTRAINT FK_5811829554177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room_issue ADD CONSTRAINT FK_581182955E7AA58C FOREIGN KEY (issue_id) REFERENCES issue (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE room DROP CONSTRAINT FK_729F519B166D1F9C');
        $this->addSql('ALTER TABLE room_issue DROP CONSTRAINT FK_5811829554177093');
        $this->addSql('ALTER TABLE room_issue DROP CONSTRAINT FK_581182955E7AA58C');
        $this->addSql('DROP TABLE room');
        $this->addSql('DROP TABLE room_issue');
    }
}
