<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241118124110 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE issue_project_tag (issue_id INT NOT NULL, project_tag_id INT NOT NULL, PRIMARY KEY(issue_id, project_tag_id))');
        $this->addSql('CREATE INDEX IDX_F3B938C45E7AA58C ON issue_project_tag (issue_id)');
        $this->addSql('CREATE INDEX IDX_F3B938C4AD76885B ON issue_project_tag (project_tag_id)');
        $this->addSql('CREATE TABLE project_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, project_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_91F26D60166D1F9C ON project_tag (project_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_91F26D60166D1F9C5E237E06 ON project_tag (project_id, name)');
        $this->addSql('ALTER TABLE issue_project_tag ADD CONSTRAINT FK_F3B938C45E7AA58C FOREIGN KEY (issue_id) REFERENCES issue (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue_project_tag ADD CONSTRAINT FK_F3B938C4AD76885B FOREIGN KEY (project_tag_id) REFERENCES project_tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_tag ADD CONSTRAINT FK_91F26D60166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE issue_project_tag DROP CONSTRAINT FK_F3B938C45E7AA58C');
        $this->addSql('ALTER TABLE issue_project_tag DROP CONSTRAINT FK_F3B938C4AD76885B');
        $this->addSql('ALTER TABLE project_tag DROP CONSTRAINT FK_91F26D60166D1F9C');
        $this->addSql('DROP TABLE issue_project_tag');
        $this->addSql('DROP TABLE project_tag');
    }
}
