<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241219111415 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE issue_dependency (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, issue_id INT NOT NULL, dependency_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B9102E595E7AA58C ON issue_dependency (issue_id)');
        $this->addSql('CREATE INDEX IDX_B9102E59C2F67723 ON issue_dependency (dependency_id)');
        $this->addSql('ALTER TABLE issue_dependency ADD CONSTRAINT FK_B9102E595E7AA58C FOREIGN KEY (issue_id) REFERENCES issue (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue_dependency ADD CONSTRAINT FK_B9102E59C2F67723 FOREIGN KEY (dependency_id) REFERENCES issue (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE issue_dependency DROP CONSTRAINT FK_B9102E595E7AA58C');
        $this->addSql('ALTER TABLE issue_dependency DROP CONSTRAINT FK_B9102E59C2F67723');
        $this->addSql('DROP TABLE issue_dependency');
    }
}
