WEBSOCKET ws://localhost:3000/projects/projectid/rooms/qwerty?eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA1MjA2MzUsImlkIjoiMTIzNDU2Nzg5MCIsImZ1bGxOYW1lIjoiSm9obiBTbWl0aCJ9.noNPLkdfuL27F4vF4guhs4vDLF0IgaQTVHQH5EGzECk
Content-Type: application/json
